import type { TabId } from "./flows";

export type LogLine = {
  level: "info" | "success" | "warn" | "error";
  text: string;
};

export const consoleLogs: Record<TabId, LogLine[]> = {
  "data-surgeon": [
    { level: "info", text: "Initializing Data Surgeon v2.1..." },
    { level: "info", text: "Loading user profile → age=23, income=₹15,00,000" },
    { level: "info", text: "Running schema validation on 12 required fields..." },
    { level: "info", text: "annual_income_inr: ✓  (₹15,00,000)" },
    { level: "info", text: "monthly_expenses_inr: ✓  (₹45,000)" },
    { level: "info", text: "dependents: ✓  (2 dependents)" },
    { level: "info", text: "assets.equity_stocks_inr: ✓  (₹3,00,000)" },
    { level: "info", text: "assets.crypto_inr: ✓  (₹1,00,000)" },
    { level: "info", text: "liabilities.education_loan_inr: ✓  (₹4,00,000)" },
    { level: "info", text: "insurance.term_cover_inr: ✓  (₹0 — flagging)" },
    { level: "warn", text: "EPF balance ₹80,000 seems low for income bracket → assuming recent graduate" },
    { level: "warn", text: "No HRA data provided → will use standard deductions" },
    { level: "info", text: "Computing Data Quality Score across 12 dimensions..." },
    { level: "success", text: "✓  Data Quality Score: 92 / 100" },
    { level: "success", text: "✓  Verification complete — 2 advisory flags raised" },
  ],

  "tax-wizard": [
    { level: "info", text: "Tax Wizard initializing..." },
    { level: "info", text: "Loading income data: ₹15,00,000 p.a." },
    { level: "info", text: "Parsing deductions: EPF ₹80,000, Health insurance ₹0" },
    { level: "info", text: "Computing Old Regime tax liability..." },
    { level: "info", text: "Old Regime: 5% (₹2.5–5L) → 20% (₹5–10L) → 30% (>₹10L)" },
    { level: "info", text: "Taxable income (Old): ₹12,50,000" },
    { level: "info", text: "Old Regime tax = ₹1,82,500" },
    { level: "info", text: "Computing New Regime tax liability..." },
    { level: "info", text: "New Regime: 5% → 10% → 15% → 20% slabs applied" },
    { level: "info", text: "New Regime tax = ₹1,56,000" },
    { level: "success", text: "✓  New Regime saves ₹26,500 (14.5%) — recommending New Regime" },
    { level: "warn", text: "Section 80C limit unutilized by ₹70,000 (only EPF ₹80k claimed of ₹1.5L)" },
    { level: "warn", text: "No NPS (Section 80CCD(1B)) contribution detected — additional ₹50k deduction available" },
    { level: "success", text: "✓  Tax strategy compiled" },
  ],

  "portfolio-xray": [
    { level: "info", text: "Portfolio X-Ray initializing asset scan..." },
    { level: "info", text: "Total portfolio value: ₹5,30,000" },
    { level: "info", text: "Equity stocks: ₹3,00,000 → 56.6%" },
    { level: "info", text: "Crypto: ₹1,00,000 → 18.9%" },
    { level: "info", text: "Bank balance: ₹50,000 → 9.4%" },
    { level: "info", text: "EPF: ₹80,000 → 15.1%" },
    { level: "info", text: "Running target allocation model for age=23, risk=aggressive..." },
    { level: "info", text: "Target: Equity 70%, Debt/Cash 25%, Crypto ≤5%" },
    { level: "error", text: "CRITICAL: Crypto exposure 18.9% >> recommended < 5% — rebalancing required" },
    { level: "error", text: "CRITICAL: Emergency fund ₹50,000 < required ₹1,35,000 (3× monthly expenses)" },
    { level: "info", text: "Goal-corpus gap analysis: retirement corpus required ₹4.8Cr" },
    { level: "success", text: "✓  Portfolio report compiled — 2 critical actions identified" },
  ],

  "risk-shield": [
    { level: "info", text: "Risk Shield initializing..." },
    { level: "info", text: "Analysing debt profile: education loan ₹4,00,000" },
    { level: "info", text: "Monthly EMI: ₹12,000 → 9.6% of monthly income" },
    { level: "success", text: "EMI stress: SAFE (< 40% threshold)" },
    { level: "info", text: "Running Human Life Value (HLV) calculation..." },
    { level: "info", text: "HLV = Annual Income × Income Replacement Period × Multiplier" },
    { level: "info", text: "HLV = ₹15L × 10 × 15 = ₹2,25,00,000" },
    { level: "info", text: "Checking current insurance coverage..." },
    { level: "error", text: "CRITICAL: Term life cover = ₹0 (no policy found)" },
    { level: "error", text: "CRITICAL: Insurance deficit = ₹2,25,00,000 with 2 dependents at risk" },
    { level: "info", text: "Recommendation: ₹2.5Cr term plan before age 25 → ~₹800/month premium" },
    { level: "success", text: "✓  Risk report compiled — 1 critical gap, immediate action required" },
  ],

  "fire-planner": [
    { level: "info", text: "FIRE Planner initializing..." },
    { level: "info", text: "Annual lifestyle expense: ₹5,40,000 (₹45,000 × 12)" },
    { level: "info", text: "Applying 4% safe-withdrawal rule (25× expenses)..." },
    { level: "info", text: "Base Freedom Number = ₹5,40,000 / 0.04 = ₹1,35,00,000" },
    { level: "info", text: "Adjusting for inflation 6% over 22 years to target age 45..." },
    { level: "info", text: "Inflation multiplier = (1.06)^22 = 3.60" },
    { level: "info", text: "Inflation-adjusted Freedom Number = ₹4,80,00,000" },
    { level: "info", text: "Current corpus: ₹5,30,000 (equity + EPF + cash)" },
    { level: "info", text: "Gap to FIRE: ₹4,74,70,000" },
    { level: "info", text: "Computing required SIP at 12% annualised return over 22 years..." },
    { level: "success", text: "✓  Required monthly SIP: ₹35,000" },
    { level: "success", text: "✓  FIRE roadmap compiled → projected retirement age: 45" },
  ],

  "exec-narrator": [
    { level: "info", text: "Exec Narrator loading all 5 agent reports..." },
    { level: "info", text: "Ingesting Data Surgeon → DQ Score 92, 2 flags" },
    { level: "info", text: "Ingesting Tax Wizard → New Regime saves ₹26,500" },
    { level: "info", text: "Ingesting Portfolio X-Ray → Crypto 19%, Emergency fund low" },
    { level: "info", text: "Ingesting Risk Shield → ₹2.25Cr insurance deficit (CRITICAL)" },
    { level: "info", text: "Ingesting FIRE Planner → SIP ₹35,000/mo, retire at 45" },
    { level: "info", text: "Running impact × urgency scoring across 8 action items..." },
    { level: "info", text: "Synthesising executive summary..." },
    { level: "success", text: "Priority 1: Build Emergency Fortress — pause equity, save ₹1.35L" },
    { level: "success", text: "Priority 2: Close Risk Gap — buy ₹2.5Cr term insurance immediately" },
    { level: "success", text: "Priority 3: Optimise Tax Regime — New Regime + NPS saves ₹26,500" },
    { level: "success", text: "✓  Gold Strategy compiled — 3 priority actions identified" },
  ],

  warroom: [
    { level: "info", text: "⚔️  War Room deploying 6 agents..." },
    { level: "info", text: "Loading blackboard: user_id=demo_23y_SE" },
    { level: "info", text: "Personas detected: YOUNG_INVESTOR, UNDER_INSURED, AGGRESSIVE_INVESTOR" },
    { level: "info", text: "Persona engine confidence: Rule-Based 0.85, K-Means 0.70, LLM 1.0" },
    { level: "info", text: "[Data Surgeon] Initializing schema validation..." },
    { level: "success", text: "[Data Surgeon] ✓  DQ Score: 92/100 — writing to blackboard" },
    { level: "info", text: "[Tax Wizard] Computing Old vs New regime comparison..." },
    { level: "success", text: "[Tax Wizard] ✓  New Regime saves ₹26,500 — writing to blackboard" },
    { level: "info", text: "[Portfolio X-Ray] Scanning ₹5.3L portfolio allocation..." },
    { level: "warn", text: "[Portfolio X-Ray] ⚠  Crypto 18.9% >> 5% target — flagging rebalance" },
    { level: "info", text: "[Risk Shield] Computing Human Life Value for 2 dependents..." },
    { level: "error", text: "[Risk Shield] ✗  CRITICAL: ₹2.25Cr insurance gap — no term cover" },
    { level: "info", text: "[FIRE Planner] Calculating Freedom Number at 6% inflation..." },
    { level: "success", text: "[FIRE Planner] ✓  Target ₹4.8Cr by age 45 — SIP ₹35,000/mo" },
    { level: "info", text: "[Exec Narrator] Synthesising Gold Strategy from 5 reports..." },
    { level: "success", text: "[Exec Narrator] ✓  Gold Strategy ready — 3 priority actions" },
    { level: "success", text: "⚔️  War Room complete" },
  ],
};
